import { useState } from 'react';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Checkbox from '@mui/material/Checkbox';
import FormControlLabel from '@mui/material/FormControlLabel';
import Paper from '@mui/material/Paper';
import TextField from '@mui/material/TextField';
import { mainPageDefaults } from '../../data/mainPageDefaults';
import { readMainPage,resetMainPage,saveMainPage } from '../../hooks/useManagedMainPage';

const group={p:{xs:2,md:3},border:'1px solid #E7E8EC',borderRadius:3,bgcolor:'#fff'};
export default function MainPageManager({readOnly=false}){const [form,setForm]=useState(readMainPage);const nested=(groupName,key,value)=>setForm(p=>({...p,[groupName]:{...p[groupName],[key]:value}}));const section=(name,key,value)=>setForm(p=>({...p,sections:{...p.sections,[name]:{...p.sections[name],[key]:value}}}));const reset=()=>{resetMainPage();setForm(mainPageDefaults);};return <Box sx={{p:{xs:2,md:3},bgcolor:'#F8F8FA'}}><Box sx={{display:'flex',flexWrap:'wrap',justifyContent:'space-between',gap:2,mb:3}}><Box><Box sx={{fontSize:24,fontWeight:900}}>메인페이지 관리</Box><Box sx={{color:'#737780',mt:.5}}>배너, 타임라인과 콘텐츠 영역 문구를 수정하고 노출 여부를 관리합니다.</Box></Box><Box sx={{display:'flex',gap:1}}><Button variant="outlined" onClick={()=>window.open(`${import.meta.env.BASE_URL}#/`,'_blank')}>미리보기</Button>{!readOnly&&<><Button variant="outlined" onClick={reset}>초기화</Button><Button variant="contained" onClick={()=>{saveMainPage(form);window.alert('메인페이지에 반영했습니다.');}} sx={{bgcolor:'#171717'}}>저장하고 반영</Button></>}</Box></Box><Box sx={{display:'grid',gap:2.5}}><Paper elevation={0} sx={group}><h3>메인 배너 문구</h3><FormControlLabel control={<Checkbox checked={form.hero.visible} onChange={e=>nested('hero','visible',e.target.checked)}/>} label="배너 문구 노출"/><Box sx={{display:'grid',gap:2,mt:1}}><TextField label="메인 문구" value={form.hero.title} onChange={e=>nested('hero','title',e.target.value)}/><TextField label="서브 문구" value={form.hero.subtitle} onChange={e=>nested('hero','subtitle',e.target.value)}/><TextField label="버튼 문구" value={form.hero.buttonText} onChange={e=>nested('hero','buttonText',e.target.value)}/></Box></Paper><Paper elevation={0} sx={group}><h3>대여 타임라인</h3><FormControlLabel control={<Checkbox checked={form.timeline.visible} onChange={e=>nested('timeline','visible',e.target.checked)}/>} label="타임라인 노출"/><TextField fullWidth sx={{mt:1}} label="타임라인 제목" value={form.timeline.title} onChange={e=>nested('timeline','title',e.target.value)}/></Paper>{Object.entries(form.sections).map(([name,data])=><Paper key={name} elevation={0} sx={group}><h3>{{hanbok:'콘텐츠 1 · 전통한복',world:'콘텐츠 2 · 세계의상',cosplay:'콘텐츠 3 · 코스프레',stage:'콘텐츠 4 · 공연의상'}[name]}</h3><FormControlLabel control={<Checkbox checked={data.visible} onChange={e=>section(name,'visible',e.target.checked)}/>} label="영역 노출"/><Box sx={{display:'grid',gap:2,mt:1}}><TextField label="제목" value={data.title} onChange={e=>section(name,'title',e.target.value)}/><TextField multiline minRows={3} label="소개 문구" value={data.desc} onChange={e=>section(name,'desc',e.target.value)}/></Box></Paper>)}<Paper elevation={0} sx={group}><h3>플로팅 아이콘 이미지</h3><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1fr 1fr'},gap:2}}><TextField label="챗봇 이미지 경로" value={form.chatbotIcon} onChange={e=>setForm(p=>({...p,chatbotIcon:e.target.value}))}/><TextField label="상담하기 이미지 경로" value={form.consultIcon} onChange={e=>setForm(p=>({...p,consultIcon:e.target.value}))}/></Box></Paper></Box></Box>}
