import { useState } from 'react';
import { Link } from 'react-router-dom';
import Box from '@mui/material/Box';
import Button from '@mui/material/Button';
import Chip from '@mui/material/Chip';
import Checkbox from '@mui/material/Checkbox';
import FormControlLabel from '@mui/material/FormControlLabel';
import Rating from '@mui/material/Rating';
import ShoppingBagOutlinedIcon from '@mui/icons-material/ShoppingBagOutlined';
import LocalShippingOutlinedIcon from '@mui/icons-material/LocalShippingOutlined';
import ReplayRoundedIcon from '@mui/icons-material/ReplayRounded';
import VerifiedOutlinedIcon from '@mui/icons-material/VerifiedOutlined';
import PlayArrowRoundedIcon from '@mui/icons-material/PlayArrowRounded';
import Footer from '../components/common/Footer';
import { useStore } from '../store/StoreContext';
import { asset } from '../utils/asset';
import { FONTS } from '../theme/tokens';
import useManagedDetailPage from '../hooks/useManagedDetailPage';

const sectionSx={width:'min(1180px,90%)',mx:'auto',py:{xs:7,md:11}};
const imageUrl=(src)=>/^https?:|^data:|^blob:/.test(src||'')?src:asset(src);

export default function NezukoDetailPage({product}){
  const detail=useManagedDetailPage();
  const {addToCart,setDialog,cart}=useStore();
  const gallery=[detail.images.main,detail.images.thumbnail,detail.images.worn,detail.images.accessories].filter(Boolean).map(imageUrl);
  const [active,setActive]=useState(0),[size,setSize]=useState(detail.rental.sizes[0]||'M'),[qty,setQty]=useState(1),[infoTab,setInfoTab]=useState('detail');
  const [period,setPeriod]=useState('1박');
  const [extras,setExtras]=useState({accessory:false,wig:false,props:false});
  const price=Number(detail.price)||product.price, original=Math.round(price/(1-(Number(detail.discountRate)||0)/100));
  const periodOptions=[{label:'1박',rate:1},{label:'1박 2일',rate:1.3},{label:'2박 3일',rate:1.6}];
  const extraOptions=[{key:'accessory',label:'악세사리',fee:Math.round(price*.1/100)*100},{key:'wig',label:'가발',fee:Math.round(price*.2/100)*100},{key:'props',label:'소품',fee:Math.round(price*.15/100)*100}];
  const periodRate=periodOptions.find(option=>option.label===period)?.rate||1;
  const periodPrice=Math.round(price*periodRate/100)*100;
  const extrasPrice=extraOptions.filter(option=>extras[option.key]).reduce((sum,option)=>sum+option.fee,0);
  const unitPrice=periodPrice+extrasPrice;
  const totalPrice=unitPrice*qty;
  const unavailable=detail.visibility==='품절'||detail.stockStatus==='품절';
  const inCart=cart.some(x=>x.id===product.id);
  const cartProduct={...product,name:detail.productName,price:unitPrice,basePrice:price,thumbnail:detail.images.thumbnail,images:[detail.images.main,detail.images.worn],period,rentalPeriod:period,selectedExtras:extraOptions.filter(option=>extras[option.key]).map(option=>option.label),extraFees:Object.fromEntries(extraOptions.map(option=>[option.label,option.fee]))};
  const blocks={
    detail:<Box key="detail" sx={sectionSx}><Box sx={{display:'flex',justifyContent:'center',gap:1,borderBottom:'1px solid #D9D4CE',mb:6}}>{[['detail','상세 정보'],['care','소재·관리'],['delivery','배송·교환']].map(([k,l])=><Button key={k} onClick={()=>setInfoTab(k)} sx={{color:infoTab===k?'#7C4DFF':'#777',fontWeight:900,px:{xs:1.5,md:4},py:2,borderBottom:infoTab===k?'3px solid #7C4DFF':'3px solid transparent',borderRadius:0}}>{l}</Button>)}</Box>{infoTab==='detail'&&<><Box sx={{maxWidth:820,mx:'auto',textAlign:'center'}}><Box sx={{color:'#7C4DFF',fontWeight:900}}>{detail.shortDescription}</Box><Box sx={{lineHeight:2,mt:2,color:'#625D57'}}>{detail.description}</Box></Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:4,mt:7}}>{detail.features.map((x,i)=><Box key={x} sx={{borderTop:'2px solid #171717',pt:2}}><Box sx={{color:'#7C4DFF',fontWeight:900}}>0{i+1}</Box><Box sx={{fontSize:21,fontWeight:900,my:1}}>{x}</Box><Box sx={{color:'#777',lineHeight:1.8}}>촬영과 행사에서 편안하고 완성도 높은 연출을 돕는 입어봄의 대여 구성입니다.</Box></Box>)}</Box><Box sx={{mt:7,overflowX:'auto'}}><Box component="table" sx={{width:'100%',minWidth:560,borderCollapse:'collapse','& th,& td':{border:'1px solid #DDD6CE',p:2,textAlign:'center'},'& th':{bgcolor:'#F2ECE6'}}}><thead><tr><th>사이즈</th><th>가슴</th><th>허리</th><th>총장</th></tr></thead><tbody>{detail.sizeTable.map(r=><tr key={r.size}><td>{r.size}</td><td>{r.chest}cm</td><td>{r.waist}cm</td><td>{r.length}cm</td></tr>)}</tbody></Box></Box></>}{infoTab==='care'&&<Box sx={{maxWidth:760,mx:'auto',lineHeight:2}}><b>소재</b><p>{detail.care.material}</p><b>세탁법</b><p>{detail.care.washing}</p><b>착용 주의사항</b><p>{detail.care.caution}</p></Box>}{infoTab==='delivery'&&<Box sx={{maxWidth:760,mx:'auto',lineHeight:2}}><b>배송비</b><p>{detail.delivery.fee}</p><b>도착 예정일</b><p>{detail.delivery.arrival}</p><b>반납 방법</b><p>{detail.delivery.returnMethod}</p><b>교환 안내</b><p>{detail.delivery.exchange}</p></Box>}</Box>,
    worn:<Box key="worn" sx={{bgcolor:'#F2ECE6'}}><Box sx={sectionSx}><Box sx={{textAlign:'center',color:'#7C4DFF',fontWeight:900,letterSpacing:'.12em'}}>STYLE GALLERY</Box><Box component="h2" sx={{textAlign:'center',fontFamily:FONTS.gmarket,fontSize:{xs:28,md:42},mt:1}}>의상부터 선택 소품까지 한눈에</Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'1.35fr .65fr'},gap:2,mt:5}}><Box component="img" src={imageUrl(detail.images.worn)} alt="착용 사진" sx={{width:'100%',height:{xs:480,md:760},objectFit:'cover'}}/><Box sx={{display:'grid',gap:2}}><Box component="img" src={imageUrl(detail.images.main)} alt="대표 상품" sx={{width:'100%',height:{xs:360,md:370},objectFit:'contain',bgcolor:'#fff'}}/><Box component="img" src={imageUrl(detail.images.accessories)} alt="구성품과 악세사리" sx={{width:'100%',height:{xs:360,md:370},objectFit:'cover'}}/></Box></Box><Box sx={{mt:4,p:3,bgcolor:'#fff',fontWeight:800}}>기본 상품은 의상 단품이며 악세사리·가발·소품은 대여 옵션에서 추가할 수 있습니다.</Box></Box></Box>,
    video:<Box key="video" sx={{bgcolor:'#171717',color:'#fff'}}><Box sx={sectionSx}><Box sx={{color:'#FF9DB8',fontWeight:900}}>STYLE FILM</Box><Box component="h2" sx={{fontFamily:FONTS.gmarket,fontSize:{xs:28,md:40}}}>네즈코 코스프레 착용 가이드</Box><Box sx={{position:'relative',mt:4}}><Box component="img" src={imageUrl(detail.images.worn)} alt="착용 영상 미리보기" sx={{width:'100%',maxHeight:650,objectFit:'cover',opacity:.72}}/><Box sx={{position:'absolute',inset:0,display:'grid',placeItems:'center'}}><Button aria-label="영상 재생" sx={{minWidth:84,width:84,height:84,borderRadius:'50%',bgcolor:'#fff',color:'#171717'}}><PlayArrowRoundedIcon sx={{fontSize:48}}/></Button></Box></Box></Box></Box>,
    reviews:<Box key="reviews" sx={sectionSx}><Box sx={{color:'#7C4DFF',fontWeight:900}}>REAL REVIEW</Box><Box component="h2" sx={{fontFamily:FONTS.gmarket,fontSize:{xs:28,md:40}}}>네즈코를 진짜로 입어봄</Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',md:'repeat(3,1fr)'},gap:3,mt:4}}>{detail.reviews.filter(r=>r.visible).map((r,i)=><Box key={`${r.author}-${i}`} sx={{borderTop:'2px solid #171717',pt:2}}><Rating value={Number(r.rating)} precision={.5} readOnly size="small"/><Box component="img" src={imageUrl(r.image)} alt={`${r.author} 후기`} sx={{width:'100%',aspectRatio:'4/5',objectFit:'cover',my:2}}/><Box sx={{fontWeight:900}}>{r.author} · 실제 대여 후기</Box><Box sx={{lineHeight:1.75,my:1.5}}>{r.text}</Box></Box>)}</Box></Box>
  };
  return <Box sx={{bgcolor:'#FFFDF8',color:'#171717',fontFamily:FONTS.pretendard}}>
    {detail.visibility!=='공개'&&<Box sx={{bgcolor:'#FFF1C8',p:1.5,textAlign:'center',fontWeight:900}}>관리자 미리보기 · 현재 상태: {detail.visibility}</Box>}
    <Box component="header" sx={{height:76,px:{xs:2,md:6},display:'flex',alignItems:'center',justifyContent:'space-between',borderBottom:'1px solid #E6E0D8',bgcolor:'rgba(255,253,248,.96)',position:'sticky',top:0,zIndex:30}}><Link to="/"><Box sx={{fontFamily:FONTS.gmarket,fontSize:22,letterSpacing:'.08em'}}>IBUBOM</Box></Link><Box sx={{display:{xs:'none',md:'flex'},gap:4,fontWeight:700}}><Link to="/">전통한복</Link><Link to="/">세계의상</Link><Link to="/">코스프레</Link><Link to="/">공연의상</Link></Box><Button onClick={()=>setDialog('cart')} startIcon={<ShoppingBagOutlinedIcon/>} sx={{color:'#171717',fontWeight:800}}>장바구니 {cart.length}</Button></Box>
    <Box sx={{width:'min(1320px,92%)',mx:'auto',py:3,color:'#756F68',fontSize:13}}>홈 · 코스프레 · {detail.category} · <b>{detail.productName}</b></Box>
    <Box sx={{width:'min(1320px,92%)',mx:'auto',display:'grid',gridTemplateColumns:{xs:'1fr',lg:'1.15fr .85fr'},gap:{xs:4,lg:8},pb:10}}><Box><Box sx={{position:'relative',bgcolor:'#F2ECE6',overflow:'hidden'}}><Box component="img" src={gallery[active]} alt={detail.productName} sx={{width:'100%',aspectRatio:'4/5',objectFit:'contain'}}/><Box sx={{position:'absolute',right:16,bottom:14,bgcolor:'rgba(23,23,23,.75)',color:'#fff',px:1.5,py:.6,fontSize:12}}>{active+1} / {gallery.length}</Box></Box><Box sx={{display:'grid',gridTemplateColumns:`repeat(${gallery.length},1fr)`,gap:1,mt:1}}>{gallery.map((src,i)=><Box key={`${src}${i}`} component="button" onClick={()=>setActive(i)} sx={{border:i===active?'2px solid #7C4DFF':'1px solid #DED8D1',bgcolor:'#fff',p:0,cursor:'pointer'}}><Box component="img" src={src} alt="" sx={{width:'100%',aspectRatio:'1',objectFit:'cover'}}/></Box>)}</Box></Box>
      <Box sx={{pt:{lg:3}}}><Box sx={{color:'#7C4DFF',fontWeight:900,letterSpacing:'.12em',fontSize:12}}>IBUBOM · {detail.category}</Box><Box component="h1" sx={{fontFamily:FONTS.gmarket,fontSize:{xs:34,md:48},lineHeight:1.15,mt:2,mb:2}}>{detail.productName}</Box><Box sx={{color:'#6E6862',fontSize:16,lineHeight:1.8}}>{detail.shortDescription}</Box><Box sx={{display:'flex',alignItems:'center',gap:1,my:3}}><Rating value={4.9} precision={.5} readOnly/><b>4.9</b><Box sx={{color:'#777'}}>실제 대여 후기</Box></Box><Box sx={{display:'flex',alignItems:'baseline',gap:2,mb:4}}><Box sx={{fontSize:34,fontWeight:900}}>{price.toLocaleString()}원</Box>{detail.discountRate>0&&<><Box sx={{textDecoration:'line-through',color:'#999'}}>{original.toLocaleString()}원</Box><Box sx={{color:'#FF5C8A',fontWeight:900}}>{detail.discountRate}%</Box></>}</Box><Chip label={unavailable?'품절':detail.stockStatus} color={unavailable?'error':'success'} variant="outlined"/>
        <Box sx={{borderTop:'1px solid #DDD6CE',pt:3,mt:3}}><Box sx={{fontWeight:900,mb:1.5}}>사이즈 선택</Box><Box sx={{display:'flex',gap:1,flexWrap:'wrap'}}>{detail.rental.sizes.map(s=><Button key={s} variant={size===s?'contained':'outlined'} onClick={()=>setSize(s)} disabled={!detail.rental.sizeStock[s]} sx={{minWidth:72,py:1.4,bgcolor:size===s?'#171717':'#fff',color:size===s?'#fff':'#171717',borderColor:'#171717',fontSize:16,fontWeight:900}}>{s}</Button>)}</Box><Box sx={{fontSize:12,color:'#777',mt:1.5}}>{detail.rental.sizes.map(s=>`${s} ${detail.rental.sizeStock[s]||0}벌`).join(' · ')}</Box></Box>
        <Box sx={{mt:3}}><Box sx={{fontWeight:900,fontSize:17}}>대여 기간 <Box component="span" sx={{fontSize:12,color:'#7C4DFF'}}>· 한 가지 필수 선택</Box></Box><Box sx={{display:'grid',gridTemplateColumns:{xs:'1fr',sm:'repeat(3,1fr)'},gap:1.2,mt:1.5}}>{periodOptions.map(option=><Button key={option.label} variant={period===option.label?'contained':'outlined'} onClick={()=>setPeriod(option.label)} sx={{minHeight:66,py:1.5,bgcolor:period===option.label?'#7C4DFF':'#fff',color:period===option.label?'#fff':'#171717',borderColor:'#7C4DFF',fontSize:16,fontWeight:900,display:'flex',flexDirection:'column'}}>{option.label}<Box component="span" sx={{fontSize:12,fontWeight:600,mt:.4}}>{option.rate===1?'기본 금액':`+${Math.round((option.rate-1)*100)}%`}</Box></Button>)}</Box></Box>
        <Box sx={{mt:3,p:2.5,bgcolor:'#F6F1FF',borderRadius:2}}><Box sx={{fontWeight:900,fontSize:17,mb:1}}>추가 대여 옵션 <Box component="span" sx={{fontSize:12,color:'#777'}}>· 선택 사항</Box></Box>{extraOptions.map(option=><FormControlLabel key={option.key} sx={{display:'flex',m:0,py:.5}} control={<Checkbox checked={extras[option.key]} onChange={e=>setExtras(prev=>({...prev,[option.key]:e.target.checked}))} sx={{'& .MuiSvgIcon-root':{fontSize:28}}}/>} label={<Box sx={{display:'flex',justifyContent:'space-between',gap:3,minWidth:190,fontWeight:800}}><span>{option.label}</span><span>+{option.fee.toLocaleString()}원</span></Box>}/>)}</Box>
        <Box sx={{display:'flex',alignItems:'center',justifyContent:'space-between',py:3,mt:3,borderTop:'1px solid #DDD6CE',borderBottom:'1px solid #DDD6CE'}}><b>수량</b><Box sx={{display:'flex',alignItems:'center',border:'1px solid #CCC'}}><Button onClick={()=>setQty(Math.max(1,qty-1))} sx={{fontSize:20,minWidth:52}}>−</Button><Box sx={{px:2,fontWeight:900}}>{qty}</Box><Button onClick={()=>setQty(Math.min(detail.rental.quantity,qty+1))} sx={{fontSize:20,minWidth:52}}>+</Button></Box></Box>
        <Box sx={{my:3,p:2.5,bgcolor:'#171717',color:'#fff',borderRadius:2}}><Box sx={{display:'flex',justifyContent:'space-between',fontSize:13,color:'#CCC',mb:1}}><span>{period} {periodRate>1?`(+${Math.round((periodRate-1)*100)}%)`:''}</span><span>{periodPrice.toLocaleString()}원</span></Box>{extrasPrice>0&&<Box sx={{display:'flex',justifyContent:'space-between',fontSize:13,color:'#CCC',mb:1}}><span>추가 옵션</span><span>+{extrasPrice.toLocaleString()}원</span></Box>}<Box sx={{display:'flex',justifyContent:'space-between',alignItems:'baseline',fontSize:18,borderTop:'1px solid #555',pt:1.5}}><span>총 대여금액</span><b style={{fontSize:30}}>{totalPrice.toLocaleString()}원</b></Box></Box>
        <Button fullWidth disabled={unavailable} variant="contained" onClick={()=>addToCart({...cartProduct,size,qty})} sx={{bgcolor:'#7C4DFF',py:2.2,fontSize:19,fontWeight:900,mb:1.5}}>{unavailable?'품절된 상품입니다':inCart?'장바구니에 담긴 상품':'선택한 옵션으로 장바구니 담기'}</Button><Box sx={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',mt:4,borderTop:'1px solid #DDD6CE',borderBottom:'1px solid #DDD6CE'}}>{[[LocalShippingOutlinedIcon,'도착 안내',detail.delivery.arrival],[ReplayRoundedIcon,'간편 반납',detail.delivery.returnMethod],[VerifiedOutlinedIcon,'세탁 완료',detail.care.washing]].map(([Icon,t,d])=><Box key={t} sx={{textAlign:'center',py:2.5,px:1,borderRight:'1px solid #DDD6CE','&:last-child':{borderRight:0}}}><Icon/><Box sx={{fontWeight:900,mt:.5}}>{t}</Box><Box sx={{fontSize:11,color:'#777'}}>{d}</Box></Box>)}</Box></Box></Box>
    {detail.sectionOrder.map(k=>blocks[k])}<Footer/>
  </Box>;
}
